# Generated by Django 5.0.3 on 2025-12-07 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
