# Generated by Django 5.0.3 on 2026-01-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_weightentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightentry',
            name='diastolic_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='systolic_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
